config/routes.rb
Rails.application.routes.draw do
  root 'airs#index'

  resources :airs do
    member do
      post :update_air
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/air.rb
class Air < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/airs_controller.rb
class AirsController < ApplicationController
  def index
    @airs = Air.all
  end

  def update_air
    air = Air.find(params[:id])

    response = RestClient.get "http://web.juhe.cn:8080/environment/air/pm",
                              :params => { :city => "chongqing", :key => JUHE_CONFIG["api_key"] }

    data = JSON.parse(response.body)

    air.update( :city => data["result"][0]["city"],
                :pm_two_five => data["result"][0]["PM2.5"],
                :aqi => data["result"][0]["AQI"],
                :quality => data["result"][0]["quality"],
                :pm_ten => data["result"][0]["PM10"],
                :time => data["result"][0]["time"]
              )

    redirect_to airs_path
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/helpers/airs_helper.rb
module AirsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/airs/index.html.erb
<script src="//cdn.bootcss.com/Chart.js/2.5.0/Chart.bundle.js"></script>

<section id="chart">
  <% @airs.each do |air| %>

  <canvas id="myChart" width="400" height="400"></canvas>
  <script>
  var ctx = document.getElementById("myChart");
  var myChart = new Chart(ctx, {
      type: 'bar',
      data: {
          labels: ["PM2.5", "AOI", "PM10"],
          datasets: [{
              label: 'Air Chart',
              data: [<%= air.pm_two_five %>, <%= air.aqi %>, <%= air.pm_ten %>],
              backgroundColor: [
                  'rgba(255, 99, 132, 0.2)',
                  'rgba(54, 162, 235, 0.2)',
                  'rgba(255, 206, 86, 0.2)',
              ],
              borderColor: [
                  'rgba(255,99,132,1)',
                  'rgba(54, 162, 235, 1)',
                  'rgba(255, 206, 86, 1)',
              ],
              borderWidth: 1
          }]
      },
      options: {
          scales: {
              yAxes: [{
                  ticks: {
                      beginAtZero:true
                  }
              }]
          }
      }
  });
  </script>

  <div class="text-center">
    <%= link_to "更新", update_air_air_path(air), :method => :post, class: "btn btn-info" %>
    <%= air.city %>
    <%= air.quality %>
    <%= air.time %>
  </div>

  <% end %>

</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AirChart</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="container">
    <%= yield %>
  </body>
</html>